image: python:3.6

stages:
- build
- test

# python is mainly used for api gen bindings and system tests
before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r requirements-dev.txt

ldc-build:
  image: dlang2/ldc-ubuntu:1.13.0
  stage: build
  script:
    - dub build --build=release --compiler=ldc

dmd-build:
  image: dlang2/dmd-ubuntu:2.084.0
  stage: build
  script:
    - dub build --build=release

# python36:
#   image: python:3.6
#   stage: test
#   script: pytest -s -vv tests/unit
