variables:
  NVIMHOST_LOG_FILE: "/tmp/nvimhost_log.txt"
  NVIM_LISTEN_ADDRESS: "/tmp/nvim_test_addr"

stages:
- build
- test

# ./Dockerfile.nvim, inherents from dlang2/ldc-ubuntu:1.13.0
image: registry.gitlab.com/viniarck/nvimhost-d/ldc-ubuntu:1.13.0

ldc-build:
  stage: build
  script:
    - ldc2 --version
    - dub build --build=release --compiler=ldc2 --arch=x86_64
    - dub build --build=release --compiler=ldc2 --arch=x86_64 --config=demoaltfile
    - dub build --build=release --compiler=ldc2 --arch=x86_64 --config=demoplugin
    - dub build --build=release --compiler=ldc2 --arch=x86_64 --config=nvimclient
    - cp ./bin/demo-plugin /usr/local/bin
    - which demo-plugin
  only:
    changes:
      - source/**
      - system_tests/**
  artifacts:
    paths:
     - ./bin

ldc-unit-tests:
  stage: test
  only:
    changes:
      - source/**
      - system_tests/**
  script:
    - dub test --build=release --compiler=ldc2 --arch=x86_64

ldc-system-tests:
  stage: test
  only:
    changes:
      - source/**
      - system_tests/**
  script:
    - nvim --version
    - cp ./bin/altfile-plugin /usr/local/bin
    - cp ./bin/demo-plugin /usr/local/bin
    - cp ./bin/nvim-client /usr/local/bin
    - which demo-plugin
    - pip3 install -r requirements-dev.txt
    - python3 -m pytest -s -vv system_tests/test_demo_plugin_bootstrap.py --tb=short
    - python3 -m pytest -s -vv system_tests/test_demo_plugin_functions.py --tb=short

## dmd compiler

dmd-build:
  image: dlang2/dmd-ubuntu:2.084.0
  stage: build
  only:
    changes:
      - source/**
      - system_tests/**
  script:
    - dmd --version
    - dub build --build=release --arch=x86_64
    - dub build --build=release --compiler=dmd --arch=x86_64 --config=demoaltfile
    - dub build --build=release --compiler=dmd --arch=x86_64 --config=demoplugin
    - dub build --build=release --compiler=dmd --arch=x86_64 --config=nvimclient

dmd-unit-tests:
  image: dlang2/dmd-ubuntu:2.084.0
  stage: test
  only:
    changes:
      - source/**
      - system_tests/**
  script:
    - dub test --build=release --arch=x86_64
